export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Australia: [
    "Adelaide",
    "Brisbane",
    "Canberra",
    "Darwin",
    "Gold Coast",
    "Hobart",
    "Melbourne",
    "Perth",
    "Sydney",
  ],
  Brazil: [
    "Belo Horizonte",
    "Brasília",
    "Curitiba",
    "Fortaleza",
    "Manaus",
    "Rio de Janeiro",
    "Salvador",
    "São Paulo",
  ],
  Canada: [
    "Calgary",
    "Edmonton",
    "Hamilton",
    "Kitchener",
    "Montreal",
    "Ottawa",
    "Quebec City",
    "Toronto",
    "Vancouver",
    "Winnipeg",
  ],
  China: [
    "Beijing",
    "Chengdu",
    "Guangzhou",
    "Hangzhou",
    "Nanjing",
    "Shanghai",
    "Shenzhen",
    "Wuhan",
    "Xi'an",
  ],
  France: [
    "Bordeaux",
    "Lyon",
    "Marseille",
    "Montpellier",
    "Nantes",
    "Nice",
    "Paris",
    "Strasbourg",
    "Toulouse",
  ],
  Germany: [
    "Berlin",
    "Cologne",
    "Dortmund",
    "Düsseldorf",
    "Frankfurt",
    "Hamburg",
    "Leipzig",
    "Munich",
    "Stuttgart",
  ],
  India: [
    "Ahmedabad",
    "Bangalore",
    "Chennai",
    "Delhi",
    "Hyderabad",
    "Jaipur",
    "Kochi",
    "Kolkata",
    "Lucknow",
    "Mumbai",
    "Pune",
    "Surat",
  ],
  Italy: [
    "Bologna",
    "Florence",
    "Genoa",
    "Milan",
    "Naples",
    "Palermo",
    "Rome",
    "Turin",
  ],
  Japan: [
    "Fukuoka",
    "Hiroshima",
    "Kobe",
    "Kyoto",
    "Nagoya",
    "Osaka",
    "Sapporo",
    "Tokyo",
    "Yokohama",
  ],
  Mexico: [
    "Guadalajara",
    "Juárez",
    "León",
    "Mexico City",
    "Monterrey",
    "Puebla",
    "Tijuana",
  ],
  Netherlands: ["Amsterdam", "Eindhoven", "Rotterdam", "The Hague", "Utrecht"],
  Nigeria: [
    "Abuja",
    "Benin City",
    "Enugu",
    "Ibadan",
    "Kano",
    "Lagos",
    "Maiduguri",
    "Port Harcourt",
  ],
  Pakistan: [
    "Faisalabad",
    "Islamabad",
    "Karachi",
    "Lahore",
    "Multan",
    "Peshawar",
    "Quetta",
    "Rawalpindi",
  ],
  "Saudi Arabia": [
    "Dammam",
    "Jeddah",
    "Khobar",
    "Mecca",
    "Medina",
    "Riyadh",
    "Tabuk",
  ],
  Singapore: ["Singapore"],
  "South Africa": [
    "Bloemfontein",
    "Cape Town",
    "Durban",
    "Johannesburg",
    "Port Elizabeth",
    "Pretoria",
  ],
  Spain: [
    "Barcelona",
    "Bilbao",
    "Madrid",
    "Málaga",
    "Seville",
    "Valencia",
    "Zaragoza",
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Ajman",
    "Al Ain",
    "Dubai",
    "Ras Al Khaimah",
    "Sharjah",
  ],
  "United Kingdom": [
    "Birmingham",
    "Bristol",
    "Cardiff",
    "Edinburgh",
    "Glasgow",
    "Leeds",
    "Liverpool",
    "London",
    "Manchester",
    "Sheffield",
  ],
  "United States": [
    "Atlanta",
    "Austin",
    "Berkeley",
    "Boston",
    "Chicago",
    "Dallas",
    "Denver",
    "Houston",
    "Jacksonville",
    "Los Angeles",
    "Miami",
    "Nashville",
    "New York",
    "Philadelphia",
    "Phoenix",
    "San Antonio",
    "San Diego",
    "San Francisco",
    "San Jose",
    "Seattle",
  ],
};
